[features]
seeds = false
[programs.devnet]
questbook = "FE2wm72uyHc7vXE8X6WCVrePq9L8MFh7EpDFsLQXNRZv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/gyan/config/solana/devnet-test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/index.ts"
